name: Apache2-PPI-HTML
version: 0.01
abstract: mod_perl2 interface to PPI::HTML syntax highlighter
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  CGI: 3.10
  mod_perl: 2.0
  PPI: 0.994
  PPI::HTML: 0.05
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
